name = "ClimaComms"
uuid = "3a4d1b5c-c61d-41fd-a00a-5873ba7a1b0d"
authors = [
    "Kiran Pamnany <clima-software@caltech.edu>",
    "Simon Byrne <simonbyrne@caltech.edu>",
    "Charles Kawczynski <charliek@caltech.edu>",
    "Sriharsha Kandala <Sriharsha.kvs@gmail.com>",
    "Jake Bolewski <clima-software@caltech.edu>",
    "Gabriele Bozzola <gbozzola@caltech.edu>",
]
version = "0.6.3"

[weakdeps]
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
MPI = "da04e1cc-30fd-572f-bb4f-1f8673147195"

[extensions]
ClimaCommsCUDAExt = "CUDA"
ClimaCommsMPIExt = "MPI"

[compat]
CUDA = "3, 4, 5"
MPI = "0.20.18"
julia = "1.9"
