name = "ClimaComms"
uuid = "3a4d1b5c-c61d-41fd-a00a-5873ba7a1b0d"
authors = ["CliMA Contributors <clima-software@caltech.edu>"]
version = "0.3.1"

[deps]
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
KernelAbstractions = "63c18a36-062a-441e-b654-da1e3ab1ce7c"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
CUDA = "3"
KernelAbstractions = "0.7"
StaticArrays = "1"
julia = "1.7"
