name = "ClimaComms"
uuid = "3a4d1b5c-c61d-41fd-a00a-5873ba7a1b0d"
authors = ["CliMA Contributors <clima-software@caltech.edu>"]
version = "0.4.0"

[deps]
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
MPI = "da04e1cc-30fd-572f-bb4f-1f8673147195"

[compat]
CUDA = "3, 4"
MPI = "0.20.6"
julia = "1.8"
