agents:
  queue: central
  slurm_mem: 8G
  modules: julia/1.9.3 cuda/12.2 ucx/1.14.1_cuda-12.2 openmpi/4.1.5_cuda-12.2 hdf5/1.12.2-ompi415 nsight-systems/2023.2.1

env:
  JULIA_LOAD_PATH: "${JULIA_LOAD_PATH}:${BUILDKITE_BUILD_CHECKOUT_PATH}/.buildkite"
  JULIA_CUDA_USE_BINARYBUILDER: false
  JULIA_CUDA_MEMORY_POOL: none
  OPENBLAS_NUM_THREADS: 1

steps:
  - label: "initialize"
    key: "initialize"
    command:
      - echo "--- Instantiate project"
      - "julia --project -e 'using Pkg; Pkg.instantiate(;verbose=true); Pkg.precompile(;strict=true)'"
      # force the initialization of the CUDA runtime as it is lazily loaded by default
      - "julia --project -e 'using CUDA; CUDA.precompile_runtime()'"
      - "julia --project -e 'using Pkg; Pkg.status()'"

      - "julia --project=test/test_artifacts -e 'using Pkg; Pkg.develop(;path=\".\"); Pkg.instantiate()'"

    agents:
      slurm_cpus_per_task: 8
    env:
      JULIA_NUM_PRECOMPILE_TASKS: 8

  - wait

  - label: ":computer: tests"
    key: "cpu_tests"
    command:
      - julia --project -e 'using Pkg; Pkg.test()'
    env:
      CLIMACOMMS_TEST_DEVICE: CPU
    agents:
      slurm_nodes: 1
      slurm_ntasks_per_node: 4

  - label: ":computer: threaded tests"
    key: "cpu_threaded_tests"
    command:
      - julia --threads 8 --project -e 'using Pkg; Pkg.test()'
    env:
      CLIMACOMMS_TEST_DEVICE: CPU
    agents:
      slurm_cpus_per_task: 8

  - label: ":flower_playing_cards: tests"
    key: "gpu_tests"
    command:
      - julia --project -e 'using Pkg; Pkg.test()'
    env:
      CLIMACOMMS_TEST_DEVICE: CUDA
    agents:
      slurm_nodes: 1
      slurm_ntasks_per_node: 2
      slurm_gpus_per_task: 1

  # The artifacts jobs cannot be concurrent
  - label: ":amphora: artifacts"
    key: "artifacts"
    command:
      - julia --project=test/test_artifacts test/test_artifacts/test_clima_artifacts.jl
    env:
      CLIMACOMMS_TEST_DEVICE: CPU
    agents:
      slurm_nodes: 1
      slurm_ntasks_per_node: 1
    concurrency: 1
    concurrency_group: 'artifacts'

  - label: ":amphora::amphora: artifacts (MPI)"
    key: "mpi_artifacts"
    command:
      - julia --project=test/test_artifacts test/test_artifacts/test_clima_artifacts.jl
    env:
      CLIMACOMMS_TEST_DEVICE: CPU
    agents:
      slurm_nodes: 1
      slurm_ntasks_per_node: 2
    concurrency: 1
    concurrency_group: 'artifacts'
