agents:
  queue: new-central
  slurm_mem: 8G
  modules: climacommon/2024_03_18

env:
  OPENBLAS_NUM_THREADS: 1

steps:
  - label: "initialize"
    key: "initialize"
    command:
      - echo "--- Instantiate project"
      - "julia --project -e 'using Pkg; Pkg.instantiate(;verbose=true); Pkg.precompile(;strict=true)'"
      # force the initialization of the CUDA runtime as it is lazily loaded by default
      - "julia --project -e 'using CUDA; CUDA.precompile_runtime()'"
      - "julia --project -e 'using Pkg; Pkg.status()'"

      - "julia --project=test -e 'using Pkg; Pkg.develop(;path=\".\"); Pkg.instantiate(;verbose=true); Pkg.precompile(;strict=true)'"

    agents:
      slurm_gpus: 1
      slurm_cpus_per_task: 8
    env:
      JULIA_NUM_PRECOMPILE_TASKS: 8

  - wait

  - label: ":computer: tests"
    key: "cpu_tests"
    command:
      - julia --project=test test/runtests.jl
    env:
      CLIMACOMMS_TEST_DEVICE: CPU
    agents:
      slurm_nodes: 1
      slurm_ntasks_per_node: 4

  - label: ":computer: threaded tests"
    key: "cpu_threaded_tests"
    command:
      - julia --threads 8 --project=test test/runtests.jl
    env:
      CLIMACOMMS_TEST_DEVICE: CPU
    agents:
      slurm_cpus_per_task: 8

  - label: ":flower_playing_cards: tests"
    key: "gpu_tests"
    command:
      - julia --project=test test/runtests.jl
    env:
      CLIMACOMMS_TEST_DEVICE: CUDA
    agents:
      slurm_nodes: 1
      slurm_ntasks_per_node: 2
      slurm_gpus_per_task: 1
